# https://wiki.hypr.land/Hypr-Ecosystem/hyprpaper/

splash = true
ipc = true
wallpaper {
    monitor = eDP-1
    # Use absolute path instead of ~/
                                                                                                                                                                                                                                        path = /home/ramonwest/wokemarchy-mac/wallpapers/wp15319239-1252246482.jpg
    fit_mode = cover
}
