# https://wiki.hypr.land/Hypr-Ecosystem/hyprpaper/

splash = true
ipc = true
wallpaper {
    monitor = eDP-1
    # Use absolute path instead of ~/
    path = $HOME/wokemarchy-mac/wallpapers/1-city-view.png
    fit_mode = cover
}
